#app config
server:
  servlet:
    context-path: /api/v2/
  port: 8088
spring:
  profiles:
    active: default
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: publiciteApp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: brice
    password: brice
    properties:
      mail:
        SMTP:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_SECRET_KEY_EXPIRATION}
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      picture-output-path: ./upload
app:
  integrator:
    siteIid: ${INTEGRATOR_API_SITE_ID}
    apiKey: ${INTEGRATOR_API_KEY}
    paymentUrl: ${INTEGRATOR_API_PAYMENT_URL}
    ngrockUrl: https://0447-2c0f-f0f8-6bf-f700-3d47-529b-ae0a-f0eb.ngrok-free.app