spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/panneau_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        #show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: localhost
    port: 1025
    username: brice
    password: brice
    properties:
      mail:
        SMTP:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      secret-key: 23563deebf828c77de9bd80d0357671bfd66065b42963ee7137f50cdabdf1235
      expiration: 86480000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      picture-output-path: ./upload

server:
  servlet:
    context-path: /api/v1/
  port: 8088
app:
  integrator:
    siteIid: 734813
    apiKey: 167092646965f9bbfa807873.13817346
    paymentUrl: https://api-checkout.cinetpay.com/v2/payment
    ngrockUrl: https://d80d-2c0f-f0f8-6bf-f700-9dd8-84c6-5779-4a71.ngrok-free.app
